version: "3.8"

services:
    # image project
    game-app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./src:/src/
            - /src/node_modules
        ports:
            - "8092:8080"
        networks:
            - appnet
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'db'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3392:3306"
        networks:
            - appnet

networks:
    appnet:
        driver: bridge